### ISSUE TITLE
Guidance for non-experts in Blender is missing

### ISSUE THREAD

**Issue by galou** [cole-bsmr/collidergen#2]
As a novice in Blender, I'm missing instructions where the tools can be found.

Thanks!

**Comment by ColeOSRF** [comment]
Hey galou. After installing and activating the addon in the preferences menu, you can press "N" or the little arrow on the left side of the right pane. This will open up the "N-panel" where the "Collider Gen" tab is. 
![image](https://github.com/cole-bsmr/collidergen/assets/42189537/7b13d3d6-fc0b-427d-9e86-84a116796893)
