### ISSUE TITLE
RuntimeError when deselecting object

### ISSUE THREAD

**Issue by Yadunund** [cole-bsmr/collidergen#4]
Hi Cole!

Thanks for this excellent tool. I think I might have uncovered an edge case that throws an error.

Steps to reproduce:
1. Import stl mesh
2. Select mesh and click Create->Cylinder.
3. Press X,Y or Z to create the collider
4. Press Esc (error will be thrown)

![image](https://github.com/cole-bsmr/collidergen/assets/13482049/3746cce9-09ac-44df-8b49-eb4ffd462a11)

**Comment by cole-bsmr** [comment]
Thanks for the bug hunting Yadu! I've updated the addon to fix this issue along with some other fixes. Please re-open this issue if the problem still persists for you with the new version but it seems to be fixed in my testing.
